# Generated by Django 5.1.5 on 2025-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('endereco', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
